# Plot Viual Odometry

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from copy import copy

def transform(t_x, t_y, t_z, r_x, r_y, r_z, r_w):
    return np.asarray(
        [[1-2*r_y**2-2*r_z**2, 2*r_x*r_y-2*r_z*r_w, 2*r_x*r_z+2*r_y*r_w, t_x],
         [2*r_x*r_y+2*r_z*r_w, 1-2*r_x**2-2*r_z**2, 2*r_y*r_z-2*r_x*r_w, t_y],
         [2*r_x*r_z-2*r_y*r_w, 2*r_y*r_z+2*r_x*r_w, 1-2*r_x**2-2*r_y**2, t_z],
         [0,0,0,1]])
# https://en.wikipedia.org/wiki/Rotation_matrix#General_rotations

In [2]:
df = pd.read_csv("/home/torsten/ms/data/rosbag2_2023_06_21-05_37_55/vo.csv")
df

timestamp           t_x           t_y           t_z       r_x  \
0     1687341198 -1.625407e-05 -1.244574e-05 -4.873309e-05  0.000000   
1     1687341259  2.016457e-07  1.455325e-08 -3.030925e-07  0.000000   
2     1687340329 -8.859580e-14  2.710610e-13 -5.506706e-14  0.000000   
3     1687340397  3.330669e-15  5.828671e-16 -2.220446e-15  0.000000   
4     1687340456  2.627522e-03  1.311804e-03  3.900251e-03  0.000043   
...          ...           ...           ...           ...       ...   
2231  1687341067  2.327449e-07  1.686645e-07 -8.009211e-07  0.000000   
2232  1687341142  2.199299e-04 -1.129398e-03 -2.040089e-03 -0.000198   
2233  1687341208  7.678047e-05 -7.170402e-05 -1.544256e-04 -0.000009   
2234  1687341264 -1.984008e-08  1.722396e-08  3.684439e-09  0.000000   
2235  1687341332 -2.460686e-08  1.067965e-08 -8.521311e-08  0.000000   

           r_y       r_z  r_w  
0     0.000000  0.000000  1.0  
1     0.000000  0.000000  1.0  
2     0.000000  0.000000  1.0  
3     0.000000  0.000000  1.0  
4    -0.000068 -0.000159  1.0  
...        ...       ...  ...  
2231  0.000000  0.000000  1.0  
2232 -0.000053 -0.000019  1.0  
2233 -0.000008 -0.000006  1.0  
2234  0.000000  0.000000  1.0  
2235  0.000000  0.000000  1.0  

[2236 rows x 8 columns]

In [3]:
df_kf = pd.read_csv("/home/torsten/ms/data/rosbag2_2023_06_21-05_37_55/kf.csv")
df_kf

timestamp       t_x       t_y       t_z       r_x       r_y       r_z  \
0   1687340945  0.581486 -0.050316 -1.921209 -0.013981 -0.021642 -0.013101   
1   1687340866 -0.251871  0.107150  1.994880  0.002220 -0.044183  0.012639   
2   1687340372  0.094818 -0.032737  2.044571 -0.004362  0.007255 -0.006938   
3   1687340394  0.026764 -0.012133  2.020029 -0.000248 -0.001219  0.005604   
4   1687341317 -0.001175  0.000103  2.023226  0.002654  0.001491  0.003516   
5   1687341313 -0.001463 -0.007828  2.053440 -0.000530  0.004001  0.003747   
6   1687341328  0.015819  0.006905  2.016451  0.004050 -0.002205  0.008922   
7   1687340981  0.131869 -0.016057  1.995825 -0.001709  0.035250 -0.010601   
8   1687340598  0.185788  0.009570  0.588236  0.000045  0.129073 -0.001184   
9   1687341110  0.141943 -0.003480  0.623704 -0.000744  0.129264  0.004024   
10  1687340982  0.294717 -0.042103  0.831832 -0.004738  0.127222  0.002155   
11  1687340461  0.204704  0.053387  1.049185  0.002467  0.130980  0.001856   
12  1687340727  0.210133 -0.121408  0.922049 -0.008560  0.126276 -0.000844   
13  1687340740  0.225376  0.026969  1.267042 -0.000403  0.128294 -0.006358   
14  1687341256  0.195652 -0.058626  0.618125 -0.009067  0.129756 -0.008365   
15  1687340400  0.190812 -0.011816  0.407777  0.000999  0.126949  0.001404   
16  1687340554  0.189799 -0.000197  0.413073 -0.000167  0.132551  0.001654   
17  1687340742  0.178870  0.002524  0.431779  0.003614  0.129335 -0.004041   
18  1687340873  0.321038 -0.018855  1.483899 -0.003010  0.126459 -0.011305   
19  1687340673  0.479290  0.019151  2.014734  0.003109  0.091954  0.000399   
20  1687340754  0.055553  0.002396  2.055559  0.000557 -0.002577 -0.001276   
21  1687340804 -0.049354 -0.029490  2.032525 -0.001046 -0.010880  0.000925   
22  1687340874  0.076704  0.025503  2.043527 -0.002999 -0.004862 -0.002228   
23  1687340965  0.052901 -0.038631  2.042946 -0.000603 -0.000509  0.000269   
24  1687340955  0.023883  0.047084  2.051605  0.002863  0.000562 -0.002350   
25  1687340980  0.017009 -0.043482  2.040763 -0.008266  0.002289 -0.001441   
26  1687341041 -0.000457 -0.041539  2.024030 -0.001939  0.002529 -0.005415   
27  1687340959  0.029783 -0.049528  2.022679  0.000754 -0.000005 -0.000962   
28  1687340958 -0.010682  0.012280  2.065742  0.002696  0.002995 -0.003560   
29  1687340701  0.003904 -0.008949  2.030860 -0.000700  0.013445 -0.007597   
30  1687340633  0.096453 -0.015379  2.037309 -0.005799  0.019608 -0.004729   
31  1687340567 -0.074598  0.035992  1.712639  0.013352  0.126547 -0.004387   
32  1687341362  0.106212 -0.030669  0.197018 -0.015415  0.126152 -0.000786   
33  1687340444  0.111853 -0.010275  0.157052 -0.004890  0.136601 -0.002229   
34  1687341257  0.093308  0.003585  0.099510  0.002624  0.128050  0.001848   
35  1687341222  0.158890 -0.008493  0.151841 -0.001368  0.127859  0.001266   
36  1687340655  0.223594 -0.019759  0.509116 -0.003922  0.129045 -0.005072   
37  1687340856  0.161553 -0.061068  2.052612 -0.001820  0.060173  0.004475   
38  1687340594  0.206655 -0.016102  1.606979  0.002621  0.131190 -0.002139   
39  1687341323  0.220056  0.027912  0.455594  0.010173  0.138375  0.003979   
40  1687340863  0.187951 -0.018395  0.419108 -0.000978  0.132159 -0.003662   
41  1687340455  0.199198 -0.009546  0.381744 -0.002105  0.131675 -0.001002   
42  1687341056  0.188444  0.001456  0.451534  0.000633  0.127303  0.001233   
43  1687341283  0.131633 -0.002963  2.031623  0.000183 -0.036479  0.004018   
44  1687341395  0.262011 -0.005567  2.045722  0.004470  0.094966  0.001070   
45  1687340471  0.159715  0.007939  2.014969  0.000262  0.046126  0.008435   
46  1687340608  0.018705 -0.014903  2.003857  0.007651 -0.017299 -0.000097   

         r_w  
0   0.999584  
1   0.998942  
2   0.999941  
3   0.999984  
4   0.999989  
5   0.999985  
6   0.999950  
7   0.999321  
8   0.991635  
9   0.991602  
10  0.991861  
11  0.991381  
12  0.991958  
13  0.991716  
14  0.991470  
15  0.991908  
16  0

In [4]:
poses = []
poses_kf = []
last_tf = transform(0,0,0,0,0,0,1)
#"""
for i, row in df.iterrows():
    tf = transform(row["t_x"], row["t_y"], row["t_z"], row["r_x"], row["r_y"], row["r_z"], row["r_w"])
    #print(tf)
    #last_tf = np.matmul(tf, last_tf)
    last_tf = np.matmul(last_tf, tf)
    poses.append(copy(last_tf))

last_tf = transform(0,0,0,0,0,0,1)
for i, row in df_kf.iterrows():
    tf = transform(row["t_x"], row["t_y"], row["t_z"], row["r_x"], row["r_y"], row["r_z"], row["r_w"])
    #print(tf)
    #last_tf = np.matmul(tf, last_tf)
    last_tf = np.matmul(last_tf, tf)
    poses_kf.append(copy(last_tf))
#"""

    
print(last_tf)


    

[[ 0.98282929 -0.16837632 -0.07547692  2.92214665]
 [ 0.16944988  0.98550629  0.00800667 -1.83385476]
 [ 0.07303485 -0.02065872  0.99711579 -3.81589575]
 [ 0.          0.          0.          1.        ]]


In [5]:
"""
poses.append(transform(0,0,0,0,0,0,1))

for i in range(3):
    tf =transform(0.2,0,0,0,0.707,0,0.707)
    last_tf = np.matmul(tf, last_tf)
    poses.append(copy(last_tf))

#poses.append(transform(2,0,0,0,0,0,1))
#poses.append(transform(3,0,0,0,0,0,1))
"""


'\nposes.append(transform(0,0,0,0,0,0,1))\n\nfor i in range(3):\n    tf =transform(0.2,0,0,0,0.707,0,0.707)\n    last_tf = np.matmul(tf, last_tf)\n    poses.append(copy(last_tf))\n\n#poses.append(transform(2,0,0,0,0,0,1))\n#poses.append(transform(3,0,0,0,0,0,1))\n'

In [6]:
poses = np.asarray(poses)
poses.shape

(2236, 4, 4)

In [7]:
poses_kf = np.asarray(poses_kf)
poses_kf.shape

(47, 4, 4)

In [8]:
%matplotlib tk
plt.figure(figsize=(18,10))
plt.axis('equal')
plt.plot(poses[:, 0, 3], poses[:,2,3], "-x")
plt.plot(poses_kf[:, 0, 3], poses_kf[:,2,3], "-x")
for i in range(0, poses.shape[0], 100):
    plt.text(poses[i,0,3], poses[i,2,3], str(i))
plt.show()

In [9]:
#df = pd.read_csv("gpsNED.csv")
#df

In [10]:
"""
plt.figure(figsize=(18,10))
plt.scatter(df.iloc[:,0], df.iloc[:,1])
plt.show()
"""

'\nplt.figure(figsize=(18,10))\nplt.scatter(df.iloc[:,0], df.iloc[:,1])\nplt.show()\n'